### PR TITLE
basic benchmarking infra

### PR DESCRIPTION
**Pull request by mpenciak**
I set up some very basic infrastructure to do benchmarking,

Let me know how it looks, and I can build it out a bit more with better reporting/logging/analysis/useage examples

### CODE REVIEW

**Comment by arthurpaulino** [comment]
How does the current output look? 👀

**Comment by mpenciak** [comment]
Not great, right now it's the same as `Cronos.summary`. 

For example, here's the output from `Benchmark.SparseMatrix`:

```
Timings:
  1 | 0.000016s
  1024 | 0.737156s
  128 | 0.007719s
  16 | 0.000075s
  2 | 0.000009s
  2048 | 3.280704s
  256 | 0.036386s
  32 | 0.000351s
  4 | 0.000007s
  4096 | 12.316267s
  512 | 0.162786s
  64 | 0.001636s
  8 | 0.000018s
```

**Review by arthurpaulino — APPROVED** [review]
Oh, that's ok. I thought we already had results for multiplication etc

**Comment by mpenciak** [comment]
Added logging, and fixed the output so it displays in increasing input size (before it was ordered lexicographically by the string value, which was kind of annoying to analyze by hand)

Should be ready to merge if it looks good.

**Review by arthurpaulino — APPROVED** [review]

**Pull request merged**
